language: node_js
dist: trusty
node_js:
  - "node"

before_install:
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FA_NPM_TOKEN

install:
  - npm i -g npm
  - npm ci
  - npm install @fortawesome/fontawesome-pro
  - npm install @fortawesome/fontawesome-free

script:
  - npm test